### ISSUE TITLE
Sample requests for initiating backup, restore

### ISSUE THREAD

**Issue by nandanatur** [theherk/pinkopy#11]
Hey Guys,

Can someone post sample request for
- adding host to discover VM
- backup VM
- restore VM
- remove host

**Comment by theherk** [comment]
@sreenandan, I have only created this for internal use that is specific to my needs. Currently, it does not support these options. However, I made it FLOSS so that it could be improved upon by the community. It is very expandable, and the requests should be pretty simple due to how they are abstracted.

I will leave this issue open for now. I will consider adding the requests in the future. In the meantime, I'd love a PR which adds these.
